
  DROP TABLE "SALAB"."EEXTERNALLINKS" cascade constraints;
  DROP TABLE "SALAB"."ELABEVENTS" cascade constraints;
  DROP TABLE "SALAB"."EMEMBER" cascade constraints;
  DROP TABLE "SALAB"."EPUBLICATION" cascade constraints;
  DROP TABLE "SALAB"."EPUBMETAFORMAT" cascade constraints;
  DROP TABLE "SALAB"."ERESEARCHAREA" cascade constraints;
  DROP TABLE "SALAB"."ESTATUS" cascade constraints;
  DROP TABLE "SALAB"."RALUMNI" cascade constraints;
  DROP TABLE "SALAB"."RMEMBERINTEREST" cascade constraints;
  DROP TABLE "SALAB"."RPUBCATEGORY" cascade constraints;
  DROP TABLE "SALAB"."RPUBMEMBER" cascade constraints;
  DROP VIEW "SALAB"."VALUMNI";
  DROP VIEW "SALAB"."VALUMNIYEAR";
  DROP VIEW "SALAB"."VLABEVENTSTITLE";
  DROP VIEW "SALAB"."VLABMEMBERPERF";
  DROP VIEW "SALAB"."VMEMBERINTEREST";
  DROP VIEW "SALAB"."VMEMBERPUB";
  DROP VIEW "SALAB"."VPUBCOUNTS";
  DROP VIEW "SALAB"."VPUBMEMBER";
--------------------------------------------------------
--  DDL for Table EEXTERNALLINKS
--------------------------------------------------------

  CREATE TABLE "SALAB"."EEXTERNALLINKS" 
   (	"LINKID" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"LINK" VARCHAR2(255 BYTE), 
	"LINKDESC" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" 
 LOB ("LINKDESC") STORE AS BASICFILE (
  TABLESPACE "SALAB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ELABEVENTS
--------------------------------------------------------

  CREATE TABLE "SALAB"."ELABEVENTS" 
   (	"ARTICLEID" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"TEXT" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" 
 LOB ("TEXT") STORE AS BASICFILE (
  TABLESPACE "SALAB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ESTATUS
--------------------------------------------------------

  CREATE TABLE "SALAB"."ESTATUS" 
   (	"STATUSID" VARCHAR2(50 BYTE), 
	"STATUSNAME" VARCHAR2(100 BYTE), 
	"PRIORITY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Table EMEMBER
--------------------------------------------------------

  CREATE TABLE "SALAB"."EMEMBER" 
   (	"MEMBERID" VARCHAR2(50 BYTE), 
	"KORFIRSTNAME" VARCHAR2(100 BYTE), 
	"KORLASTNAME" VARCHAR2(100 BYTE), 
	"ENGFIRSTNAME" VARCHAR2(100 BYTE), 
	"ENGLASTNAME" VARCHAR2(100 BYTE), 
	"STATUSID" VARCHAR2(50 BYTE), 
	"PRIVATEWEB" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"ENTERDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Table EPUBLICATION
--------------------------------------------------------

  CREATE TABLE "SALAB"."EPUBLICATION" 
   (	"PUBID" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"PUBTYPE" VARCHAR2(50 BYTE), 
	"PUBNATION" VARCHAR2(50 BYTE), 
	"PUBDESC" CLOB, 
	"PUBDATE" DATE, 
	"USEKORNAME" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" 
 LOB ("PUBDESC") STORE AS BASICFILE (
  TABLESPACE "SALAB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EPUBMETAFORMAT
--------------------------------------------------------

  CREATE TABLE "SALAB"."EPUBMETAFORMAT" 
   (	"FORMATID" VARCHAR2(50 BYTE), 
	"FORMATSTRING" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" 
 LOB ("FORMATSTRING") STORE AS BASICFILE (
  TABLESPACE "SALAB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ERESEARCHAREA
--------------------------------------------------------

  CREATE TABLE "SALAB"."ERESEARCHAREA" 
   (	"AREAID" VARCHAR2(50 BYTE), 
	"AREANAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Table RALUMNI
--------------------------------------------------------

  CREATE TABLE "SALAB"."RALUMNI" 
   (	"MEMBERID" VARCHAR2(50 BYTE), 
	"STATUSID" VARCHAR2(50 BYTE), 
	"GRADYEAR" NUMBER(*,0), 
	"CURRENTWORK" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Table RMEMBERINTEREST
--------------------------------------------------------

  CREATE TABLE "SALAB"."RMEMBERINTEREST" 
   (	"MEMBERID" VARCHAR2(50 BYTE), 
	"AREAID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Table RPUBCATEGORY
--------------------------------------------------------

  CREATE TABLE "SALAB"."RPUBCATEGORY" 
   (	"PUBID" VARCHAR2(50 BYTE), 
	"AREAID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Table RPUBMEMBER
--------------------------------------------------------

  CREATE TABLE "SALAB"."RPUBMEMBER" 
   (	"PUBID" VARCHAR2(50 BYTE), 
	"MEMBERID" VARCHAR2(50 BYTE), 
	"REPORDER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;

---------------------------------------------------
--   DATA FOR TABLE RPUBCATEGORY
--   FILTER = none used
---------------------------------------------------
REM INSERTING into SALAB.RPUBCATEGORY
Insert into SALAB.RPUBCATEGORY (PUBID,AREAID) values ('kswb1','sa');

---------------------------------------------------
--   END DATA FOR TABLE RPUBCATEGORY
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE EMEMBER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into SALAB.EMEMBER
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('gkm','��','���','Gyeongmin','Go','msd','http://imarch.pe.kr','gkm2164@gmail.com',to_timestamp('13/03/01 00:00:00.000000000','RR/MM/DD HH24:MI:SS.FF'));
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('ah','��','��','Hwi','Ahn','phd',null,'byron1st@kaist.ac.kr',to_timestamp('12/03/01 00:00:00.000000000','RR/MM/DD HH24:MI:SS.FF'));
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('jps','��','�ʼ�','Pilsu','Jung','msd',null,'psjung@kaist.ac.kr',to_timestamp('12/03/01 00:00:00.000000000','RR/MM/DD HH24:MI:SS.FF'));
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('lhj','��','����','Heejin','Lee','msd',null,'hjlee@kaist.ac.kr',to_timestamp('12/03/01 00:00:00.000000000','RR/MM/DD HH24:MI:SS.FF'));
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('pth','��','����','Tae-hyeon','Park','phd',null,'thpark@kaist.ac.kr',to_timestamp('12/03/01 00:00:00.000000000','RR/MM/DD HH24:MI:SS.FF'));
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('kjh','��','��ȣ','Jung-ho','Kim','phd',null,null,null);
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('lsa','��','����','Seon-Ah','Lee','postd','http://www.saleese.com/',null,null);
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('kcs','��','â��','Chang-sup','Keum','phd',null,null,null);
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('ajs','��','����','Jongsun','Ahn','phd',null,null,null);
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('cys','��','����','Youn-Seok','Choi','alumni',null,null,null);
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('pds','��','�뼺','Dae-Sung','Park','alumni',null,null,null);
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('sjj','��','����','Jung-Jin','Seo','alumni',null,null,null);
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('scs','��','â��','Chang-Sun','Song','alumni',null,null,null);
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('ksw','��','����','Sungwon','Kang','prof',null,null,null);
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('hyh','��','����','Younghun','Han','phd',null,null,null);
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('ljh','��','����','Jihyun','Lee','phd',null,null,null);
Insert into SALAB.EMEMBER (MEMBERID,KORFIRSTNAME,KORLASTNAME,ENGFIRSTNAME,ENGLASTNAME,STATUSID,PRIVATEWEB,EMAIL,ENTERDATE) values ('kck','��','â��','Changki','Kim','other',null,null,null);

---------------------------------------------------
--   END DATA FOR TABLE EMEMBER
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE ERESEARCHAREA
--   FILTER = none used
---------------------------------------------------
REM INSERTING into SALAB.ERESEARCHAREA
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('se','Software Engineering');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('sa','Software Architecture');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('st','Software Testing');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('mqbsa','Measuring Quality based on Software Architecture');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('esass','Evaluation of Software Architecture Software System');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('csa','Construction of Software Architecture');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('mdd','Model-driven development');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('soa','Service Oriented Architecture');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('cs','Cloud Service');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('hci','HCI');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('ca','Context Aware');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('re','Reverse Engineering');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('nm','Network Management');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('pc','Program Comprehension');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('ci','Collective Intelligence');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('dm','Data Mining');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('cr','Code Recommendation');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('sv','Software Visualization');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('da','Dynamic Analysis');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('m&v','Modeling & Verification');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('osei','Overall Software Engineering Issues');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('spl','Software Product Line');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('reqe','Requirement Engineering');
Insert into SALAB.ERESEARCHAREA (AREAID,AREANAME) values ('splt','Software Product Line Testing');

---------------------------------------------------
--   END DATA FOR TABLE ERESEARCHAREA
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE EEXTERNALLINKS
--   FILTER = none used
---------------------------------------------------
REM INSERTING into SALAB.EEXTERNALLINKS
Insert into SALAB.EEXTERNALLINKS (LINKID,TITLE,LINK,LINKDESC) values ('l1','KAIST','http://www.kaist.ac.kr',(CLOB));
Insert into SALAB.EEXTERNALLINKS (LINKID,TITLE,LINK,LINKDESC) values ('l2','KAIST Computer Science Department','http://cs.kaist.ac.kr',(CLOB));

---------------------------------------------------
--   END DATA FOR TABLE EEXTERNALLINKS
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE ESTATUS
--   FILTER = none used
---------------------------------------------------
REM INSERTING into SALAB.ESTATUS
Insert into SALAB.ESTATUS (STATUSID,STATUSNAME,PRIORITY) values ('phd','Ph. D',3);
Insert into SALAB.ESTATUS (STATUSID,STATUSNAME,PRIORITY) values ('msd','MS. D',4);
Insert into SALAB.ESTATUS (STATUSID,STATUSNAME,PRIORITY) values ('postd','Post. D',2);
Insert into SALAB.ESTATUS (STATUSID,STATUSNAME,PRIORITY) values ('alumni','Alumni',5);
Insert into SALAB.ESTATUS (STATUSID,STATUSNAME,PRIORITY) values ('other','Other',-1);
Insert into SALAB.ESTATUS (STATUSID,STATUSNAME,PRIORITY) values ('prof','Professor',1);

---------------------------------------------------
--   END DATA FOR TABLE ESTATUS
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE RALUMNI
--   FILTER = none used
---------------------------------------------------
REM INSERTING into SALAB.RALUMNI
Insert into SALAB.RALUMNI (MEMBERID,STATUSID,GRADYEAR,CURRENTWORK) values ('cys',null,2005,'Employee at Hyundai Motors AutoEver (Present)');
Insert into SALAB.RALUMNI (MEMBERID,STATUSID,GRADYEAR,CURRENTWORK) values ('pds',null,2005,'Employee at LG Electronic (Present)');
Insert into SALAB.RALUMNI (MEMBERID,STATUSID,GRADYEAR,CURRENTWORK) values ('sjj',null,2005,'Employee at Korea Credit Bureau (Present)');
Insert into SALAB.RALUMNI (MEMBERID,STATUSID,GRADYEAR,CURRENTWORK) values ('scs',null,2006,'Employee at TTA (Present)');

---------------------------------------------------
--   END DATA FOR TABLE RALUMNI
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE EPUBLICATION
--   FILTER = none used
---------------------------------------------------
REM INSERTING into SALAB.EPUBLICATION
Insert into SALAB.EPUBLICATION (PUBID,TITLE,PUBTYPE,PUBNATION,PUBDESC,PUBDATE,USEKORNAME) values ('jk1','��ʿ���: ���Ȯ�强�� ���� ����Ʈ���� ��Ű��ó �缳��','Conference','Domestic',(CLOB),to_timestamp('09/02/09 00:00:00.000000000','RR/MM/DD HH24:MI:SS.FF'),1);
Insert into SALAB.EPUBLICATION (PUBID,TITLE,PUBTYPE,PUBNATION,PUBDESC,PUBDATE,USEKORNAME) values ('jk2','����Ʈ���� ��Ű��ó�� ���� �ý��� ���Ȯ�强 ������ ���� ����','Conference','Domestic',(CLOB),to_timestamp('07/11/21 00:00:00.000000000','RR/MM/DD HH24:MI:SS.FF'),1);
Insert into SALAB.EPUBLICATION (PUBID,TITLE,PUBTYPE,PUBNATION,PUBDESC,PUBDATE,USEKORNAME) values ('ah1','Analysis of Software Product Line Architecture Representation Mechanisms','Conference','International',(CLOB),to_timestamp('11/08/10 00:00:00.000000000','RR/MM/DD HH24:MI:SS.FF'),0);
Insert into SALAB.EPUBLICATION (PUBID,TITLE,PUBTYPE,PUBNATION,PUBDESC,PUBDATE,USEKORNAME) values ('kswb1','����Ʈ���� ��Ű��ó���� �ʴ� - ����Ʈ���� ��Ű��ó ������ �ٺ����','Books','Domestic',(CLOB),to_timestamp('12/01/01 00:00:00.000000000','RR/MM/DD HH24:MI:SS.FF'),1);
Insert into SALAB.EPUBLICATION (PUBID,TITLE,PUBTYPE,PUBNATION,PUBDESC,PUBDATE,USEKORNAME) values ('ljh1','Software Architecture Evaluation Methods Based on Cost benefit Analysis and Quantitative Decision Making','Journal','International',(CLOB),to_timestamp('09/08/01 00:00:00.000000000','RR/MM/DD HH24:MI:SS.FF'),0);

---------------------------------------------------
--   END DATA FOR TABLE EPUBLICATION
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE ELABEVENTS
--   FILTER = none used
---------------------------------------------------
REM INSERTING into SALAB.ELABEVENTS
Insert into SALAB.ELABEVENTS (ARTICLEID,TITLE,TEXT) values ('homecoming2009','Homecoming Day 2009',(CLOB));
Insert into SALAB.ELABEVENTS (ARTICLEID,TITLE,TEXT) values ('homecoming2011','Homecoming Day 2011',(CLOB));

---------------------------------------------------
--   END DATA FOR TABLE ELABEVENTS
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE RPUBMEMBER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into SALAB.RPUBMEMBER
Insert into SALAB.RPUBMEMBER (PUBID,MEMBERID,REPORDER) values ('jk1','kjh',1);
Insert into SALAB.RPUBMEMBER (PUBID,MEMBERID,REPORDER) values ('jk1','ksw',2);
Insert into SALAB.RPUBMEMBER (PUBID,MEMBERID,REPORDER) values ('jk2','kjh',1);
Insert into SALAB.RPUBMEMBER (PUBID,MEMBERID,REPORDER) values ('jk2','ksw',2);
Insert into SALAB.RPUBMEMBER (PUBID,MEMBERID,REPORDER) values ('ah1','ah',1);
Insert into SALAB.RPUBMEMBER (PUBID,MEMBERID,REPORDER) values ('ah1','ksw',2);
Insert into SALAB.RPUBMEMBER (PUBID,MEMBERID,REPORDER) values ('ljh1','ljh',1);
Insert into SALAB.RPUBMEMBER (PUBID,MEMBERID,REPORDER) values ('ljh1','ksw',2);
Insert into SALAB.RPUBMEMBER (PUBID,MEMBERID,REPORDER) values ('ljh1','kck',3);

---------------------------------------------------
--   END DATA FOR TABLE RPUBMEMBER
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE RMEMBERINTEREST
--   FILTER = none used
---------------------------------------------------
REM INSERTING into SALAB.RMEMBERINTEREST
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('ah','sa');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('ah','spl');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('ajs','sa');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('ajs','spl');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('cys','sa');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('gkm','sa');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('gkm','se');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('jps','reqe');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('jps','sa');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('jps','splt');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('kcs','cs');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('kcs','mdd');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('kcs','sa');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('kcs','soa');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('kcs','st');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('kjh','csa');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('kjh','esass');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('kjh','mqbsa');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('lhj','sa');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('lsa','ci');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('lsa','cr');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('lsa','da');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('lsa','dm');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('lsa','m&v');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('lsa','osei');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('lsa','pc');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('lsa','re');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('lsa','sa');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('lsa','sv');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('pth','sa');
Insert into SALAB.RMEMBERINTEREST (MEMBERID,AREAID) values ('pth','se');

---------------------------------------------------
--   END DATA FOR TABLE RMEMBERINTEREST
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE EPUBMETAFORMAT
--   FILTER = none used
---------------------------------------------------
REM INSERTING into SALAB.EPUBMETAFORMAT
Insert into SALAB.EPUBMETAFORMAT (FORMATID,FORMATSTRING) values ('salab-conf-dom',(CLOB));
Insert into SALAB.EPUBMETAFORMAT (FORMATID,FORMATSTRING) values ('salab-conf-int',(CLOB));
Insert into SALAB.EPUBMETAFORMAT (FORMATID,FORMATSTRING) values ('salab-default',(CLOB));
Insert into SALAB.EPUBMETAFORMAT (FORMATID,FORMATSTRING) values ('salab-jour-int',(CLOB));

---------------------------------------------------
--   END DATA FOR TABLE EPUBMETAFORMAT
---------------------------------------------------
--------------------------------------------------------
--  Constraints for Table EEXTERNALLINKS
--------------------------------------------------------

  ALTER TABLE "SALAB"."EEXTERNALLINKS" ADD CONSTRAINT "PK_EEXTERNALLINKS" PRIMARY KEY ("LINKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB"  ENABLE;
 
  ALTER TABLE "SALAB"."EEXTERNALLINKS" MODIFY ("LINKID" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."EEXTERNALLINKS" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."EEXTERNALLINKS" MODIFY ("LINK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ELABEVENTS
--------------------------------------------------------

  ALTER TABLE "SALAB"."ELABEVENTS" MODIFY ("ARTICLEID" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."ELABEVENTS" ADD PRIMARY KEY ("ARTICLEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMEMBER
--------------------------------------------------------

  ALTER TABLE "SALAB"."EMEMBER" ADD CONSTRAINT "PK_EMEMBER" PRIMARY KEY ("MEMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB"  ENABLE;
 
  ALTER TABLE "SALAB"."EMEMBER" MODIFY ("MEMBERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EPUBLICATION
--------------------------------------------------------

  ALTER TABLE "SALAB"."EPUBLICATION" ADD CONSTRAINT "PK_EPUBLICATION" PRIMARY KEY ("PUBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB"  ENABLE;
 
  ALTER TABLE "SALAB"."EPUBLICATION" MODIFY ("PUBID" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."EPUBLICATION" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."EPUBLICATION" MODIFY ("PUBTYPE" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."EPUBLICATION" MODIFY ("PUBNATION" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."EPUBLICATION" MODIFY ("PUBDESC" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."EPUBLICATION" MODIFY ("PUBDATE" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."EPUBLICATION" ADD CHECK (PubType in ('Books', 'Journal', 'Conference')) ENABLE;
 
  ALTER TABLE "SALAB"."EPUBLICATION" ADD CHECK (PubNation in ('International', 'Domestic')) ENABLE;
 
  ALTER TABLE "SALAB"."EPUBLICATION" ADD CHECK (UseKorName in (0, 1)) ENABLE;
--------------------------------------------------------
--  Constraints for Table EPUBMETAFORMAT
--------------------------------------------------------

  ALTER TABLE "SALAB"."EPUBMETAFORMAT" ADD CONSTRAINT "PK_EPUBMETAFORMAT" PRIMARY KEY ("FORMATID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB"  ENABLE;
 
  ALTER TABLE "SALAB"."EPUBMETAFORMAT" MODIFY ("FORMATID" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."EPUBMETAFORMAT" MODIFY ("FORMATSTRING" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ERESEARCHAREA
--------------------------------------------------------

  ALTER TABLE "SALAB"."ERESEARCHAREA" MODIFY ("AREAID" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."ERESEARCHAREA" MODIFY ("AREANAME" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."ERESEARCHAREA" ADD PRIMARY KEY ("AREAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTATUS
--------------------------------------------------------

  ALTER TABLE "SALAB"."ESTATUS" MODIFY ("STATUSID" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."ESTATUS" MODIFY ("STATUSNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."ESTATUS" ADD PRIMARY KEY ("STATUSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RALUMNI
--------------------------------------------------------

  ALTER TABLE "SALAB"."RALUMNI" ADD CONSTRAINT "PK_RALUMNI" PRIMARY KEY ("MEMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB"  ENABLE;
 
  ALTER TABLE "SALAB"."RALUMNI" MODIFY ("MEMBERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RMEMBERINTEREST
--------------------------------------------------------

  ALTER TABLE "SALAB"."RMEMBERINTEREST" ADD CONSTRAINT "PK_RMEMBERINTEREST" PRIMARY KEY ("MEMBERID", "AREAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB"  ENABLE;
 
  ALTER TABLE "SALAB"."RMEMBERINTEREST" MODIFY ("MEMBERID" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."RMEMBERINTEREST" MODIFY ("AREAID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RPUBCATEGORY
--------------------------------------------------------

  ALTER TABLE "SALAB"."RPUBCATEGORY" ADD CONSTRAINT "PK_RPUBCATEGORY" PRIMARY KEY ("PUBID", "AREAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB"  ENABLE;
 
  ALTER TABLE "SALAB"."RPUBCATEGORY" MODIFY ("PUBID" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."RPUBCATEGORY" MODIFY ("AREAID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RPUBMEMBER
--------------------------------------------------------

  ALTER TABLE "SALAB"."RPUBMEMBER" ADD CONSTRAINT "PK_RPUBMEMBER" PRIMARY KEY ("PUBID", "MEMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB"  ENABLE;
 
  ALTER TABLE "SALAB"."RPUBMEMBER" MODIFY ("PUBID" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."RPUBMEMBER" MODIFY ("MEMBERID" NOT NULL ENABLE);
 
  ALTER TABLE "SALAB"."RPUBMEMBER" MODIFY ("REPORDER" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Index PK_EEXTERNALLINKS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALAB"."PK_EEXTERNALLINKS" ON "SALAB"."EEXTERNALLINKS" ("LINKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Index PK_EMEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALAB"."PK_EMEMBER" ON "SALAB"."EMEMBER" ("MEMBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Index PK_EPUBLICATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALAB"."PK_EPUBLICATION" ON "SALAB"."EPUBLICATION" ("PUBID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Index PK_EPUBMETAFORMAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALAB"."PK_EPUBMETAFORMAT" ON "SALAB"."EPUBMETAFORMAT" ("FORMATID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Index PK_RALUMNI
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALAB"."PK_RALUMNI" ON "SALAB"."RALUMNI" ("MEMBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Index PK_RMEMBERINTEREST
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALAB"."PK_RMEMBERINTEREST" ON "SALAB"."RMEMBERINTEREST" ("MEMBERID", "AREAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Index PK_RPUBCATEGORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALAB"."PK_RPUBCATEGORY" ON "SALAB"."RPUBCATEGORY" ("PUBID", "AREAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;
--------------------------------------------------------
--  DDL for Index PK_RPUBMEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALAB"."PK_RPUBMEMBER" ON "SALAB"."RPUBMEMBER" ("PUBID", "MEMBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SALAB" ;


--------------------------------------------------------
--  Ref Constraints for Table EMEMBER
--------------------------------------------------------

  ALTER TABLE "SALAB"."EMEMBER" ADD CONSTRAINT "FK1_EMEMBER" FOREIGN KEY ("STATUSID")
	  REFERENCES "SALAB"."ESTATUS" ("STATUSID") ENABLE;




--------------------------------------------------------
--  Ref Constraints for Table RALUMNI
--------------------------------------------------------

  ALTER TABLE "SALAB"."RALUMNI" ADD CONSTRAINT "FK1_RALUMNI" FOREIGN KEY ("MEMBERID")
	  REFERENCES "SALAB"."EMEMBER" ("MEMBERID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "SALAB"."RALUMNI" ADD CONSTRAINT "FK2_RALUMNI" FOREIGN KEY ("STATUSID")
	  REFERENCES "SALAB"."ESTATUS" ("STATUSID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RMEMBERINTEREST
--------------------------------------------------------

  ALTER TABLE "SALAB"."RMEMBERINTEREST" ADD CONSTRAINT "FK1_RMEMBERINTEREST" FOREIGN KEY ("MEMBERID")
	  REFERENCES "SALAB"."EMEMBER" ("MEMBERID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "SALAB"."RMEMBERINTEREST" ADD CONSTRAINT "FK2_RMEMBERINTEREST" FOREIGN KEY ("AREAID")
	  REFERENCES "SALAB"."ERESEARCHAREA" ("AREAID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RPUBCATEGORY
--------------------------------------------------------

  ALTER TABLE "SALAB"."RPUBCATEGORY" ADD CONSTRAINT "FK1_RPUBCATEGORY" FOREIGN KEY ("PUBID")
	  REFERENCES "SALAB"."EPUBLICATION" ("PUBID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "SALAB"."RPUBCATEGORY" ADD CONSTRAINT "FK2_RPUBCATEGORY" FOREIGN KEY ("AREAID")
	  REFERENCES "SALAB"."ERESEARCHAREA" ("AREAID") ON DELETE SET NULL ENABLE;

--------------------------------------------------------
--  DDL for View VALUMNI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SALAB"."VALUMNI" ("GRADYEAR", "CURRENTWORK", "MEMBERID", "KORFIRSTNAME", "KORLASTNAME", "ENGFIRSTNAME", "ENGLASTNAME", "STATUSID", "PRIVATEWEB", "EMAIL", "ENTERDATE") AS 
  SELECT A.GRADYEAR, A.CURRENTWORK, M."MEMBERID",M."KORFIRSTNAME",M."KORLASTNAME",M."ENGFIRSTNAME",M."ENGLASTNAME",M."STATUSID",M."PRIVATEWEB",M."EMAIL",M."ENTERDATE"
FROM RALUMNI A, EMEMBER M
WHERE M.StatusID='alumni' AND M.MemberID=A.MemberID;
--------------------------------------------------------
--  DDL for View VALUMNIYEAR
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SALAB"."VALUMNIYEAR" ("GRADYEAR") AS 
  SELECT DISTINCT GRADYEAR
    
FROM RALUMNI;
--------------------------------------------------------
--  DDL for View VLABEVENTSTITLE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SALAB"."VLABEVENTSTITLE" ("ARTICLEID", "TITLE") AS 
  SELECT ARTICLEID, TITLE
FROM ELABEVENTS;
--------------------------------------------------------
--  DDL for View VMEMBERPUB
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SALAB"."VMEMBERPUB" ("MEMBERID", "PUBID", "TITLE", "PUBTYPE", "PUBNATION", "PUBDESC", "PUBDATE", "REPORDER") AS 
  SELECT M.MemberID, P."PUBID",P."TITLE",P."PUBTYPE",P."PUBNATION",P."PUBDESC",P."PUBDATE", RepOrder
FROM EMember M JOIN (RPubMember PM JOIN EPublication P ON PM.PubID=P.PubID) ON M.MemberID=PM.MemberID
ORDER BY RepOrder;
--------------------------------------------------------
--  DDL for View VLABMEMBERPERF
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SALAB"."VLABMEMBERPERF" ("MEMBERID", "CNTBOOKSINT", "CNTBOOKSDOM", "CNTJOURINT", "CNTJOURDOM", "CNTCONFINT", "CNTCONFDOM") AS 
  SELECT MemberID, 
COUNT (DECODE(PubType, 'Books', DECODE(PubNation, 'International', 1, null), null)) AS CntBooksInt,
COUNT (DECODE(PubType, 'Books', DECODE(PubNation, 'Domestic', 1, null), null)) AS CntBooksDom,
COUNT (DECODE(PubType, 'Journal', DECODE(PubNation, 'International', 1, null), null)) AS CntJourInt,
COUNT (DECODE(PubType, 'Journal', DECODE(PubNation, 'Domestic', 1, null), null)) AS CntJourDom,
COUNT (DECODE(PubType, 'Conference', DECODE(PubNation, 'International', 1, null), null)) AS CntConfInt,
COUNT (DECODE(PubType, 'Conference', DECODE(PubNation, 'Domestic', 1, null), null)) AS CntConfDom
FROM VMemberPub
GROUP BY MemberID, PubType, PubNation;
--------------------------------------------------------
--  DDL for View VMEMBERINTEREST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SALAB"."VMEMBERINTEREST" ("MEMBERID", "AREAID", "AREANAME") AS 
  SELECT M.MemberID, A.AreaID, A.AreaName
FROM (EMEMBER M JOIN RMEMBERINTEREST R ON M.MemberID=R.MemberID) JOIN EResearchArea A ON R.AreaID=A.AreaID;
--------------------------------------------------------
--  DDL for View VPUBCOUNTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SALAB"."VPUBCOUNTS" ("BOOKCOUNT", "JOURNALCOUNT", "CONFERENCECOUNT", "BOOKINTCNT", "BOOKDOMCNT", "JOURNINTCNT", "JOURNDOMCNT", "CONFINTCNT", "CONFDOMCNT") AS 
  SELECT
COUNT(DECODE(PubType, 'Books', 1, null)) AS BookCount,
COUNT(DECODE(PubType, 'Journal', 1, null)) AS JournalCount,
COUNT(DECODE(PubType, 'Conference', 1, null)) AS ConferenceCount,
COUNT(DECODE(PubType, 'Books', DECODE(PubNation, 'International', 1, null), null)) AS BookIntCnt,
COUNT(DECODE(PubType, 'Books', DECODE(PubNation, 'Domestic', 1, null), null)) AS BookDomCnt,
COUNT(DECODE(PubType, 'Journal', DECODE(PubNation, 'International', 1, null), null)) AS JournIntCnt,
COUNT(DECODE(PubType, 'Journal', DECODE(PubNation, 'Domestic', 1, null), null)) AS JournDomCnt,
COUNT(DECODE(PubType, 'Conference', DECODE(PubNation, 'International', 1, null), null)) AS ConfIntCnt,
COUNT(DECODE(PubType, 'Conference', DECODE(PubNation, 'Domestic', 1, null), null)) AS ConfDomCnt
FROM EPUBLICATION
GROUP BY PubType, PubNation;
--------------------------------------------------------
--  DDL for View VPUBMEMBER
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SALAB"."VPUBMEMBER" ("PUBID", "MEMBERID", "ENGFIRSTNAME", "ENGLASTNAME", "KORFIRSTNAME", "KORLASTNAME", "USEKORNAME", "REPORDER") AS 
  SELECT R.PubID,
M.MemberID,
M.ENGFIRSTNAME,
M.ENGLASTNAME,
M.KORFIRSTNAME,
M.KORLASTNAME,
P.UseKorName,
R.REPOrder
FROM
(EMEMBER M JOIN RPUBMEMBER R ON M.MemberID = R.MemberID) JOIN EPUBLICATION P ON R.PubID=P.PubID;
